fix OSCommon for Stefan

diff --git a/OSCommon/OS/configure b/OSCommon/OS/configure
--- a/OSCommon/OS/configure
+++ b/OSCommon/OS/configure
@@ -472,7 +472,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX F77 ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS FFLAGS ac_ct_F77 MPIF77 FLIBS EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS OSSRCDIR OSOBJDIR OSDOCDIR COIN_HAS_OS_TRUE COIN_HAS_OS_FALSE CPXINCDIR CPXLIB COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE LINDOINCDIR LINDOLIB COIN_HAS_LINDO_TRUE COIN_HAS_LINDO_FALSE KNITROINCDIR KNITROLIB COIN_HAS_KNITRO_TRUE COIN_HAS_KNITRO_FALSE GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE ASLLIB ASL_CPPFLAGS COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE OPENMP_TRUE OPENMP_FALSE USEMULTIPLYDEFINED_TRUE USEMULTIPLYDEFINED_FALSE YACC OSROOT_DIR oscommonlib LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX F77 ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS FFLAGS ac_ct_F77 MPIF77 FLIBS EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS OSSRCDIR OSOBJDIR OSDOCDIR COIN_HAS_OS_TRUE COIN_HAS_OS_FALSE CPPADSRCDIR CPPADOBJDIR CPPADDOCDIR COIN_HAS_CPPAD_TRUE COIN_HAS_CPPAD_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COINUTILSDOCDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE CPXINCDIR CPXLIB COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE LINDOINCDIR LINDOLIB COIN_HAS_LINDO_TRUE COIN_HAS_LINDO_FALSE KNITROINCDIR KNITROLIB COIN_HAS_KNITRO_TRUE COIN_HAS_KNITRO_FALSE GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE ASLLIB ASL_CPPFLAGS COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE OPENMP_TRUE OPENMP_FALSE USEMULTIPLYDEFINED_TRUE USEMULTIPLYDEFINED_FALSE YACC OSROOT_DIR oscommonlib coinutilslib LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -23678,7 +23678,122 @@ fi
 echo "$as_me:$LINENO: result: $coin_has_os" >&5
 echo "${ECHO_T}$coin_has_os" >&6
 
-#AC_COIN_HAS_PROJECT(cppad)
+echo "$as_me:$LINENO: checking for COIN project cppad" >&5
+echo $ECHO_N "checking for COIN project cppad... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_cppad=unavailable
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = cppad; then
+      coin_has_cppad=skipping
+    fi
+  done
+fi
+
+if test $coin_has_cppad != skipping; then
+  if test $PACKAGE_TARNAME = cppad; then
+    coin_has_cppad=.
+  else
+    if test -d $srcdir/../cppad; then
+      coin_has_cppad=../cppad
+    fi
+  fi
+fi
+
+if test $coin_has_cppad != unavailable &&
+   test $coin_has_cppad != skipping; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_CPPAD 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  CPPADSRCDIR=`cd $srcdir/$coin_has_cppad; pwd`
+
+  CPPADOBJDIR=`pwd`/$coin_has_cppad
+
+  CPPADDOCDIR=$abs_lib_dir/../share/doc/coin/cppad
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_cppad != unavailable &&
+                test $coin_has_cppad != skipping; then
+  COIN_HAS_CPPAD_TRUE=
+  COIN_HAS_CPPAD_FALSE='#'
+else
+  COIN_HAS_CPPAD_TRUE='#'
+  COIN_HAS_CPPAD_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_cppad" >&5
+echo "${ECHO_T}$coin_has_cppad" >&6
+
+echo "$as_me:$LINENO: checking for COIN project CoinUtils" >&5
+echo $ECHO_N "checking for COIN project CoinUtils... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_coinutils=unavailable
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = CoinUtils; then
+      coin_has_coinutils=skipping
+    fi
+  done
+fi
+
+if test $coin_has_coinutils != skipping; then
+  if test $PACKAGE_TARNAME = coinutils; then
+    coin_has_coinutils=.
+  else
+    if test -d $srcdir/../CoinUtils; then
+      coin_has_coinutils=../CoinUtils
+    fi
+  fi
+fi
+
+if test $coin_has_coinutils != unavailable &&
+   test $coin_has_coinutils != skipping; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_COINUTILS 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  COINUTILSSRCDIR=`cd $srcdir/$coin_has_coinutils; pwd`
+
+  COINUTILSOBJDIR=`pwd`/$coin_has_coinutils
+
+  COINUTILSDOCDIR=$abs_lib_dir/../share/doc/coin/CoinUtils
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_coinutils != unavailable &&
+                test $coin_has_coinutils != skipping; then
+  COIN_HAS_COINUTILS_TRUE=
+  COIN_HAS_COINUTILS_FALSE='#'
+else
+  COIN_HAS_COINUTILS_TRUE='#'
+  COIN_HAS_COINUTILS_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_coinutils" >&5
+echo "${ECHO_T}$coin_has_coinutils" >&6
+
 
 
 
@@ -28952,6 +29067,21 @@ case $CXX in
 esac
 
 
+if test $coin_has_coinutils != unavailable &&
+   test $coin_has_coinutils != skipping; then
+  case $CXX in
+    cl*)
+       coinutilslib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libCoinUtils.lib';;
+     *)
+       coinutilslib="-L\$(INSTALLIBDIR) -lCoinUtils";;
+  esac
+
+  else
+    { { echo "$as_me:$LINENO: error: cannot find CoinTuils which is necessary to build OS" >&5
+echo "$as_me: error: cannot find CoinTuils which is necessary to build OS" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 
 ##############################################################################
 #                   VPATH links for example input files                      #
@@ -29168,6 +29298,20 @@ if test -z "${COIN_HAS_OS_TRUE}" && test -z "${COIN_HAS_OS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_OS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"COIN_HAS_OS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_CPPAD_TRUE}" && test -z "${COIN_HAS_CPPAD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_CPPAD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_CPPAD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_COINUTILS_TRUE}" && test -z "${COIN_HAS_COINUTILS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_COINUTILS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_COINUTILS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -29881,6 +30025,16 @@ s,@OSOBJDIR@,$OSOBJDIR,;t t
 s,@OSDOCDIR@,$OSDOCDIR,;t t
 s,@COIN_HAS_OS_TRUE@,$COIN_HAS_OS_TRUE,;t t
 s,@COIN_HAS_OS_FALSE@,$COIN_HAS_OS_FALSE,;t t
+s,@CPPADSRCDIR@,$CPPADSRCDIR,;t t
+s,@CPPADOBJDIR@,$CPPADOBJDIR,;t t
+s,@CPPADDOCDIR@,$CPPADDOCDIR,;t t
+s,@COIN_HAS_CPPAD_TRUE@,$COIN_HAS_CPPAD_TRUE,;t t
+s,@COIN_HAS_CPPAD_FALSE@,$COIN_HAS_CPPAD_FALSE,;t t
+s,@COINUTILSSRCDIR@,$COINUTILSSRCDIR,;t t
+s,@COINUTILSOBJDIR@,$COINUTILSOBJDIR,;t t
+s,@COINUTILSDOCDIR@,$COINUTILSDOCDIR,;t t
+s,@COIN_HAS_COINUTILS_TRUE@,$COIN_HAS_COINUTILS_TRUE,;t t
+s,@COIN_HAS_COINUTILS_FALSE@,$COIN_HAS_COINUTILS_FALSE,;t t
 s,@CPXINCDIR@,$CPXINCDIR,;t t
 s,@CPXLIB@,$CPXLIB,;t t
 s,@COIN_HAS_CPX_TRUE@,$COIN_HAS_CPX_TRUE,;t t
@@ -29910,6 +30064,7 @@ s,@USEMULTIPLYDEFINED_FALSE@,$USEMULTIPLYDEFINED_FALSE,;t t
 s,@YACC@,$YACC,;t t
 s,@OSROOT_DIR@,$OSROOT_DIR,;t t
 s,@oscommonlib@,$oscommonlib,;t t
+s,@coinutilslib@,$coinutilslib,;t t
 s,@LIBEXT@,$LIBEXT,;t t
 s,@VPATH_DISTCLEANFILES@,$VPATH_DISTCLEANFILES,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
