work on build system

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -481,10 +481,10 @@ ac_subdirs_all="$ac_subdirs_all ThirdParty/Glpk/Glpk"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/Mumps/Mumps"
 ac_subdirs_all="$ac_subdirs_all Data/Sample"
 ac_subdirs_all="$ac_subdirs_all CoinUtils"
+ac_subdirs_all="$ac_subdirs_all Osi"
 ac_subdirs_all="$ac_subdirs_all Vol"
 ac_subdirs_all="$ac_subdirs_all DyLP"
 ac_subdirs_all="$ac_subdirs_all Clp"
-ac_subdirs_all="$ac_subdirs_all Osi"
 ac_subdirs_all="$ac_subdirs_all Cgl"
 ac_subdirs_all="$ac_subdirs_all SYMPHONY"
 ac_subdirs_all="$ac_subdirs_all Cbc"
@@ -1184,6 +1184,9 @@ Optional Packages:
   --with-coinutils-datadir
                           directory with data files for using project
                           CoinUtils
+  --with-osi-lib linker flags for using project Osi
+  --with-osi-incdir directory with header files for using project Osi
+  --with-osi-datadir directory with data files for using project Osi
   --with-vol-lib linker flags for using project Vol
   --with-vol-incdir directory with header files for using project Vol
   --with-vol-datadir directory with data files for using project Vol
@@ -1193,9 +1196,6 @@ Optional Packages:
   --with-clp-lib linker flags for using project Clp
   --with-clp-incdir directory with header files for using project Clp
   --with-clp-datadir directory with data files for using project Clp
-  --with-osi-lib linker flags for using project Osi
-  --with-osi-incdir directory with header files for using project Osi
-  --with-osi-datadir directory with data files for using project Osi
   --with-cgl-lib linker flags for using project Cgl
   --with-cgl-incdir directory with header files for using project Cgl
   --with-cgl-datadir directory with data files for using project Cgl
@@ -22096,6 +22096,123 @@ echo "${ECHO_T}no" >&6
 fi
 
 
+echo "$as_me:$LINENO: checking whether project Osi is available" >&5
+echo $ECHO_N "checking whether project Osi is available... $ECHO_C" >&6
+
+coin_has_osi=notGiven
+coin_have_project_dir=no
+
+# check if user wants to skip project in any case
+
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = "Osi"; then
+      coin_has_osi=skipping
+    fi
+    if test $dir = "/Osi"; then
+      coin_has_osi=skipping
+    fi
+  done
+fi
+
+if test $coin_has_osi != skipping; then
+  if test $PACKAGE_TARNAME = osi; then
+    coin_has_osi=.
+    coin_have_project_dir=yes
+  fi
+
+
+# Check whether --with-m4_tolower(Osi)-lib or --without-m4_tolower(Osi)-lib was given.
+if test "${with_osi_lib+set}" = set; then
+  withval="$with_osi_lib"
+  coin_has_osi=installed
+fi;
+
+
+# Check whether --with-m4_tolower(Osi)-incdir or --without-m4_tolower(Osi)-incdir was given.
+if test "${with_osi_incdir+set}" = set; then
+  withval="$with_osi_incdir"
+  coin_has_osi=installed
+fi;
+
+
+# Check whether --with-m4_tolower(Osi)-datadir or --without-m4_tolower(Osi)-datadir was given.
+if test "${with_osi_datadir+set}" = set; then
+  withval="$with_osi_datadir"
+  coin_has_osi=installed
+fi;
+
+
+
+
+
+fi
+
+if test $coin_has_osi = notGiven; then
+  #check for project by using pkg-config, if pkg-config is available
+  #we are only interested in installed packages here, so we do not search in $COIN_PKG_CONFIG_PATH_UNINSTALLED
+  if test -n "$PKG_CONFIG" ; then
+    coin_save_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
+    PKG_CONFIG_PATH="$COIN_PKG_CONFIG_PATH" ; export PKG_CONFIG_PATH
+
+if test -n "$PKG_CONFIG" ; then
+  if $PKG_CONFIG --exists "osi"; then
+    OSI_VERSION=`$PKG_CONFIG --modversion "osi" 2>/dev/null`
+    coin_has_osi="$OSI_VERSION"
+  else
+    OSI_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "osi"`
+
+  fi
+else
+  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module Osi without pkg-config\"" >&5
+echo "$as_me: error: \"Cannot check for existance of module Osi without pkg-config\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+    PKG_CONFIG_PATH="$coin_save_PKG_CONFIG_PATH"
+    export PKG_CONFIG_PATH
+  fi
+fi
+
+# if not found yet, check if project is available in present directory
+if test "$coin_has_osi" = notGiven; then
+  if test -d $srcdir//Osi; then
+    # If a third argument is given, then we have to check if one one the files given in that third argument is present.
+    # If none of the files in the third argument is available, then we consider the project directory as non-existing.
+    # However, if no third argument is given, then this means that there should be no check, and existence of the directory is sufficient.
+     coin_have_project_dir=yes
+
+    if test $coin_have_project_dir = yes; then
+      coin_has_osi=Osi
+    fi
+  fi
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_osi" >&5
+echo "${ECHO_T}$coin_has_osi" >&6
+
+echo "$as_me:$LINENO: checking whether project Osi need to be configured" >&5
+echo $ECHO_N "checking whether project Osi need to be configured... $ECHO_C" >&6
+if test "$coin_have_project_dir" = yes ; then
+
+  if test -r $srcdir/Osi/configure; then
+    coin_subdirs="$coin_subdirs Osi"
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+
+subdirs="$subdirs Osi"
+
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
 echo "$as_me:$LINENO: checking whether project Vol is available" >&5
 echo $ECHO_N "checking whether project Vol is available... $ECHO_C" >&6
 
@@ -22436,123 +22553,6 @@ echo "${ECHO_T}yes" >&6
 
 
 subdirs="$subdirs Clp"
-
-  else
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-  fi
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
-echo "$as_me:$LINENO: checking whether project Osi is available" >&5
-echo $ECHO_N "checking whether project Osi is available... $ECHO_C" >&6
-
-coin_has_osi=notGiven
-coin_have_project_dir=no
-
-# check if user wants to skip project in any case
-
-if test x"$COIN_SKIP_PROJECTS" != x; then
-  for dir in $COIN_SKIP_PROJECTS; do
-    if test $dir = "Osi"; then
-      coin_has_osi=skipping
-    fi
-    if test $dir = "/Osi"; then
-      coin_has_osi=skipping
-    fi
-  done
-fi
-
-if test $coin_has_osi != skipping; then
-  if test $PACKAGE_TARNAME = osi; then
-    coin_has_osi=.
-    coin_have_project_dir=yes
-  fi
-
-
-# Check whether --with-m4_tolower(Osi)-lib or --without-m4_tolower(Osi)-lib was given.
-if test "${with_osi_lib+set}" = set; then
-  withval="$with_osi_lib"
-  coin_has_osi=installed
-fi;
-
-
-# Check whether --with-m4_tolower(Osi)-incdir or --without-m4_tolower(Osi)-incdir was given.
-if test "${with_osi_incdir+set}" = set; then
-  withval="$with_osi_incdir"
-  coin_has_osi=installed
-fi;
-
-
-# Check whether --with-m4_tolower(Osi)-datadir or --without-m4_tolower(Osi)-datadir was given.
-if test "${with_osi_datadir+set}" = set; then
-  withval="$with_osi_datadir"
-  coin_has_osi=installed
-fi;
-
-
-
-
-
-fi
-
-if test $coin_has_osi = notGiven; then
-  #check for project by using pkg-config, if pkg-config is available
-  #we are only interested in installed packages here, so we do not search in $COIN_PKG_CONFIG_PATH_UNINSTALLED
-  if test -n "$PKG_CONFIG" ; then
-    coin_save_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
-    PKG_CONFIG_PATH="$COIN_PKG_CONFIG_PATH" ; export PKG_CONFIG_PATH
-
-if test -n "$PKG_CONFIG" ; then
-  if $PKG_CONFIG --exists "osi"; then
-    OSI_VERSION=`$PKG_CONFIG --modversion "osi" 2>/dev/null`
-    coin_has_osi="$OSI_VERSION"
-  else
-    OSI_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "osi"`
-
-  fi
-else
-  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module Osi without pkg-config\"" >&5
-echo "$as_me: error: \"Cannot check for existance of module Osi without pkg-config\"" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-    PKG_CONFIG_PATH="$coin_save_PKG_CONFIG_PATH"
-    export PKG_CONFIG_PATH
-  fi
-fi
-
-# if not found yet, check if project is available in present directory
-if test "$coin_has_osi" = notGiven; then
-  if test -d $srcdir//Osi; then
-    # If a third argument is given, then we have to check if one one the files given in that third argument is present.
-    # If none of the files in the third argument is available, then we consider the project directory as non-existing.
-    # However, if no third argument is given, then this means that there should be no check, and existence of the directory is sufficient.
-     coin_have_project_dir=yes
-
-    if test $coin_have_project_dir = yes; then
-      coin_has_osi=Osi
-    fi
-  fi
-fi
-
-echo "$as_me:$LINENO: result: $coin_has_osi" >&5
-echo "${ECHO_T}$coin_has_osi" >&6
-
-echo "$as_me:$LINENO: checking whether project Osi need to be configured" >&5
-echo $ECHO_N "checking whether project Osi need to be configured... $ECHO_C" >&6
-if test "$coin_have_project_dir" = yes ; then
-
-  if test -r $srcdir/Osi/configure; then
-    coin_subdirs="$coin_subdirs Osi"
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-
-subdirs="$subdirs Osi"
 
   else
     echo "$as_me:$LINENO: result: no" >&5
