work on build system

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -484,8 +484,8 @@ ac_subdirs_all="$ac_subdirs_all CoinUtils"
 ac_subdirs_all="$ac_subdirs_all Vol"
 ac_subdirs_all="$ac_subdirs_all DyLP"
 ac_subdirs_all="$ac_subdirs_all Clp"
-ac_subdirs_all="$ac_subdirs_all Cgl"
 ac_subdirs_all="$ac_subdirs_all Osi"
+ac_subdirs_all="$ac_subdirs_all Cgl"
 ac_subdirs_all="$ac_subdirs_all SYMPHONY"
 ac_subdirs_all="$ac_subdirs_all Cbc"
 ac_subdirs_all="$ac_subdirs_all Ipopt"
@@ -1193,12 +1193,12 @@ Optional Packages:
   --with-clp-lib linker flags for using project Clp
   --with-clp-incdir directory with header files for using project Clp
   --with-clp-datadir directory with data files for using project Clp
-  --with-cgl-lib linker flags for using project Cgl
-  --with-cgl-incdir directory with header files for using project Cgl
-  --with-cgl-datadir directory with data files for using project Cgl
   --with-osi-lib linker flags for using project Osi
   --with-osi-incdir directory with header files for using project Osi
   --with-osi-datadir directory with data files for using project Osi
+  --with-cgl-lib linker flags for using project Cgl
+  --with-cgl-incdir directory with header files for using project Cgl
+  --with-cgl-datadir directory with data files for using project Cgl
   --with-symphony-lib linker flags for using project SYMPHONY
   --with-symphony-incdir directory with header files for using project
                           SYMPHONY
@@ -22447,123 +22447,6 @@ echo "${ECHO_T}no" >&6
 fi
 
 
-echo "$as_me:$LINENO: checking whether project Cgl is available" >&5
-echo $ECHO_N "checking whether project Cgl is available... $ECHO_C" >&6
-
-coin_has_cgl=notGiven
-coin_have_project_dir=no
-
-# check if user wants to skip project in any case
-
-if test x"$COIN_SKIP_PROJECTS" != x; then
-  for dir in $COIN_SKIP_PROJECTS; do
-    if test $dir = "Cgl"; then
-      coin_has_cgl=skipping
-    fi
-    if test $dir = "/Cgl"; then
-      coin_has_cgl=skipping
-    fi
-  done
-fi
-
-if test $coin_has_cgl != skipping; then
-  if test $PACKAGE_TARNAME = cgl; then
-    coin_has_cgl=.
-    coin_have_project_dir=yes
-  fi
-
-
-# Check whether --with-m4_tolower(Cgl)-lib or --without-m4_tolower(Cgl)-lib was given.
-if test "${with_cgl_lib+set}" = set; then
-  withval="$with_cgl_lib"
-  coin_has_cgl=installed
-fi;
-
-
-# Check whether --with-m4_tolower(Cgl)-incdir or --without-m4_tolower(Cgl)-incdir was given.
-if test "${with_cgl_incdir+set}" = set; then
-  withval="$with_cgl_incdir"
-  coin_has_cgl=installed
-fi;
-
-
-# Check whether --with-m4_tolower(Cgl)-datadir or --without-m4_tolower(Cgl)-datadir was given.
-if test "${with_cgl_datadir+set}" = set; then
-  withval="$with_cgl_datadir"
-  coin_has_cgl=installed
-fi;
-
-
-
-
-
-fi
-
-if test $coin_has_cgl = notGiven; then
-  #check for project by using pkg-config, if pkg-config is available
-  #we are only interested in installed packages here, so we do not search in $COIN_PKG_CONFIG_PATH_UNINSTALLED
-  if test -n "$PKG_CONFIG" ; then
-    coin_save_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
-    PKG_CONFIG_PATH="$COIN_PKG_CONFIG_PATH" ; export PKG_CONFIG_PATH
-
-if test -n "$PKG_CONFIG" ; then
-  if $PKG_CONFIG --exists "cgl"; then
-    CGL_VERSION=`$PKG_CONFIG --modversion "cgl" 2>/dev/null`
-    coin_has_cgl="$CGL_VERSION"
-  else
-    CGL_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "cgl"`
-
-  fi
-else
-  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module Cgl without pkg-config\"" >&5
-echo "$as_me: error: \"Cannot check for existance of module Cgl without pkg-config\"" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-    PKG_CONFIG_PATH="$coin_save_PKG_CONFIG_PATH"
-    export PKG_CONFIG_PATH
-  fi
-fi
-
-# if not found yet, check if project is available in present directory
-if test "$coin_has_cgl" = notGiven; then
-  if test -d $srcdir//Cgl; then
-    # If a third argument is given, then we have to check if one one the files given in that third argument is present.
-    # If none of the files in the third argument is available, then we consider the project directory as non-existing.
-    # However, if no third argument is given, then this means that there should be no check, and existence of the directory is sufficient.
-     coin_have_project_dir=yes
-
-    if test $coin_have_project_dir = yes; then
-      coin_has_cgl=Cgl
-    fi
-  fi
-fi
-
-echo "$as_me:$LINENO: result: $coin_has_cgl" >&5
-echo "${ECHO_T}$coin_has_cgl" >&6
-
-echo "$as_me:$LINENO: checking whether project Cgl need to be configured" >&5
-echo $ECHO_N "checking whether project Cgl need to be configured... $ECHO_C" >&6
-if test "$coin_have_project_dir" = yes ; then
-
-  if test -r $srcdir/Cgl/configure; then
-    coin_subdirs="$coin_subdirs Cgl"
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-
-subdirs="$subdirs Cgl"
-
-  else
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-  fi
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
 echo "$as_me:$LINENO: checking whether project Osi is available" >&5
 echo $ECHO_N "checking whether project Osi is available... $ECHO_C" >&6
 
@@ -22670,6 +22553,123 @@ echo "${ECHO_T}yes" >&6
 
 
 subdirs="$subdirs Osi"
+
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+echo "$as_me:$LINENO: checking whether project Cgl is available" >&5
+echo $ECHO_N "checking whether project Cgl is available... $ECHO_C" >&6
+
+coin_has_cgl=notGiven
+coin_have_project_dir=no
+
+# check if user wants to skip project in any case
+
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = "Cgl"; then
+      coin_has_cgl=skipping
+    fi
+    if test $dir = "/Cgl"; then
+      coin_has_cgl=skipping
+    fi
+  done
+fi
+
+if test $coin_has_cgl != skipping; then
+  if test $PACKAGE_TARNAME = cgl; then
+    coin_has_cgl=.
+    coin_have_project_dir=yes
+  fi
+
+
+# Check whether --with-m4_tolower(Cgl)-lib or --without-m4_tolower(Cgl)-lib was given.
+if test "${with_cgl_lib+set}" = set; then
+  withval="$with_cgl_lib"
+  coin_has_cgl=installed
+fi;
+
+
+# Check whether --with-m4_tolower(Cgl)-incdir or --without-m4_tolower(Cgl)-incdir was given.
+if test "${with_cgl_incdir+set}" = set; then
+  withval="$with_cgl_incdir"
+  coin_has_cgl=installed
+fi;
+
+
+# Check whether --with-m4_tolower(Cgl)-datadir or --without-m4_tolower(Cgl)-datadir was given.
+if test "${with_cgl_datadir+set}" = set; then
+  withval="$with_cgl_datadir"
+  coin_has_cgl=installed
+fi;
+
+
+
+
+
+fi
+
+if test $coin_has_cgl = notGiven; then
+  #check for project by using pkg-config, if pkg-config is available
+  #we are only interested in installed packages here, so we do not search in $COIN_PKG_CONFIG_PATH_UNINSTALLED
+  if test -n "$PKG_CONFIG" ; then
+    coin_save_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
+    PKG_CONFIG_PATH="$COIN_PKG_CONFIG_PATH" ; export PKG_CONFIG_PATH
+
+if test -n "$PKG_CONFIG" ; then
+  if $PKG_CONFIG --exists "cgl"; then
+    CGL_VERSION=`$PKG_CONFIG --modversion "cgl" 2>/dev/null`
+    coin_has_cgl="$CGL_VERSION"
+  else
+    CGL_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "cgl"`
+
+  fi
+else
+  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module Cgl without pkg-config\"" >&5
+echo "$as_me: error: \"Cannot check for existance of module Cgl without pkg-config\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+    PKG_CONFIG_PATH="$coin_save_PKG_CONFIG_PATH"
+    export PKG_CONFIG_PATH
+  fi
+fi
+
+# if not found yet, check if project is available in present directory
+if test "$coin_has_cgl" = notGiven; then
+  if test -d $srcdir//Cgl; then
+    # If a third argument is given, then we have to check if one one the files given in that third argument is present.
+    # If none of the files in the third argument is available, then we consider the project directory as non-existing.
+    # However, if no third argument is given, then this means that there should be no check, and existence of the directory is sufficient.
+     coin_have_project_dir=yes
+
+    if test $coin_have_project_dir = yes; then
+      coin_has_cgl=Cgl
+    fi
+  fi
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_cgl" >&5
+echo "${ECHO_T}$coin_has_cgl" >&6
+
+echo "$as_me:$LINENO: checking whether project Cgl need to be configured" >&5
+echo $ECHO_N "checking whether project Cgl need to be configured... $ECHO_C" >&6
+if test "$coin_have_project_dir" = yes ; then
+
+  if test -r $srcdir/Cgl/configure; then
+    coin_subdirs="$coin_subdirs Cgl"
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+
+subdirs="$subdirs Cgl"
 
   else
     echo "$as_me:$LINENO: result: no" >&5
