modify config.ac for osTestCode example to work

diff --git a/OS/configure b/OS/configure
--- a/OS/configure
+++ b/OS/configure
@@ -472,7 +472,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX F77 ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS FFLAGS ac_ct_F77 MPIF77 FLIBS EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS OSSRCDIR OSOBJDIR COIN_HAS_OS_TRUE COIN_HAS_OS_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE OSISRCDIR OSIOBJDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE CLPSRCDIR CLPOBJDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE CBCSRCDIR CBCOBJDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE CGLSRCDIR CGLOBJDIR COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE SYMPHONYSRCDIR SYMPHONYOBJDIR COIN_HAS_SYMPHONY_TRUE COIN_HAS_SYMPHONY_FALSE DYLPSRCDIR DYLPOBJDIR COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE VOLSRCDIR VOLOBJDIR COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE IPOPTSRCDIR IPOPTOBJDIR COIN_HAS_IPOPT_TRUE COIN_HAS_IPOPT_FALSE CPPADSRCDIR CPPADOBJDIR COIN_HAS_CPPAD_TRUE COIN_HAS_CPPAD_FALSE CPXINCDIR CPXLIB COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE LINDOINCDIR LINDOLIB COIN_HAS_LINDO_TRUE COIN_HAS_LINDO_FALSE KNITROINCDIR KNITROLIB COIN_HAS_KNITRO_TRUE COIN_HAS_KNITRO_FALSE GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE ASLLIB ASL_CPPFLAGS COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE USEMULTIPLYDEFINED_TRUE USEMULTIPLYDEFINED_FALSE YACC OSROOT_DIR oslib LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX F77 ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS FFLAGS ac_ct_F77 MPIF77 FLIBS EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS OSSRCDIR OSOBJDIR COIN_HAS_OS_TRUE COIN_HAS_OS_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE OSISRCDIR OSIOBJDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE CLPSRCDIR CLPOBJDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE CBCSRCDIR CBCOBJDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE CGLSRCDIR CGLOBJDIR COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE SYMPHONYSRCDIR SYMPHONYOBJDIR COIN_HAS_SYMPHONY_TRUE COIN_HAS_SYMPHONY_FALSE DYLPSRCDIR DYLPOBJDIR COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE VOLSRCDIR VOLOBJDIR COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE IPOPTSRCDIR IPOPTOBJDIR COIN_HAS_IPOPT_TRUE COIN_HAS_IPOPT_FALSE CPPADSRCDIR CPPADOBJDIR COIN_HAS_CPPAD_TRUE COIN_HAS_CPPAD_FALSE coinutilslib clplib osiclplib cbclib osicbclib cgllib osilib dylplib osidylplib vollib osivollib symphonylib osisymphonylib ipoptlib CPXINCDIR CPXLIB COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE LINDOINCDIR LINDOLIB COIN_HAS_LINDO_TRUE COIN_HAS_LINDO_FALSE KNITROINCDIR KNITROLIB COIN_HAS_KNITRO_TRUE COIN_HAS_KNITRO_FALSE GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE ASLLIB ASL_CPPFLAGS COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE USEMULTIPLYDEFINED_TRUE USEMULTIPLYDEFINED_FALSE YACC OSROOT_DIR oslib LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -22368,6 +22368,8 @@ echo "${ECHO_T}$coin_has_cppad" >&6
 
 
 
+
+
   case $coin_has_cppad in
      unavailable|skipping)
          { { echo "$as_me:$LINENO: error: cannot find CppAD which is necessary to build OS" >&5
@@ -22375,35 +22377,144 @@ echo "$as_me: error: cannot find CppAD which is necessary to build OS" >&2;}
    { (exit 1); exit 1; }; } ;;
   esac
 
-  case $coin_has_coinutils in
-     unavailable|skipping)
-         { { echo "$as_me:$LINENO: error: cannot find CoinUtils which is necessary to build OS" >&5
-echo "$as_me: error: cannot find CoinUtils which is necessary to build OS" >&2;}
-   { (exit 1); exit 1; }; } ;;
+if test $coin_has_coinutils != unavailable &&
+   test $coin_has_coinutils != skipping; then
+  case $CXX in
+    cl*)
+       coinutilslib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libCoinUtils.lib';;
+     *)
+       coinutilslib="-L\$(INSTALLIBDIR) -lCoinUtils";;
+  esac
+
+  else
+    { { echo "$as_me:$LINENO: error: cannot find CoinTuils which is necessary to build OS" >&5
+echo "$as_me: error: cannot find CoinTuils which is necessary to build OS" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test $coin_has_clp != unavailable &&
+   test $coin_has_clp != skipping; then
+  case $CXX in
+    cl*)
+       clplib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libClp.lib'
+       osiclplib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libOsiClp.lib';;
+     *)
+       clplib="-L\$(INSTALLIBDIR) -lClp"
+       osiclplib="-L\$(INSTALLIBDIR) -lOsiClp";;
   esac
 
 
-  case $coin_has_clp in
-     unavailable|skipping)
-         { { echo "$as_me:$LINENO: error: cannot find Clp which is necessary to build OS" >&5
+  else
+    { { echo "$as_me:$LINENO: error: cannot find Clp which is necessary to build OS" >&5
 echo "$as_me: error: cannot find Clp which is necessary to build OS" >&2;}
-   { (exit 1); exit 1; }; } ;;
+   { (exit 1); exit 1; }; }
+fi
+
+if test $coin_has_cbc != unavailable &&
+   test $coin_has_cbc != skipping; then
+  case $CXX in
+    cl*)
+       cbclib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libCbc.lib'
+       osicbclib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libOsiCbc.lib';;
+     *)
+       cbclib="-L\$(INSTALLIBDIR) -lCbc"
+       osicbclib="-L\$(INSTALLIBDIR) -lOsiCbc";;
   esac
 
-  case $coin_has_cbc in
-     unavailable|skipping)
-         { { echo "$as_me:$LINENO: error: cannot find Cbc which is necessary to build OS" >&5
+
+  else
+    { { echo "$as_me:$LINENO: error: cannot find Cbc which is necessary to build OS" >&5
 echo "$as_me: error: cannot find Cbc which is necessary to build OS" >&2;}
-   { (exit 1); exit 1; }; } ;;
+   { (exit 1); exit 1; }; }
+fi
+
+
+if test $coin_has_cgl != unavailable &&
+   test $coin_has_cgl != skipping; then
+  case $CXX in
+    cl*)
+       cgllib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libCgl.lib';;
+     *)
+       cgllib="-L\$(INSTALLIBDIR) -lCgl";;
   esac
 
-  case $coin_has_cgl in
-     unavailable|skipping)
-         { { echo "$as_me:$LINENO: error: cannot find Cgl which is necessary to build OS" >&5
+  else
+    { { echo "$as_me:$LINENO: error: cannot find Cgl which is necessary to build OS" >&5
 echo "$as_me: error: cannot find Cgl which is necessary to build OS" >&2;}
-   { (exit 1); exit 1; }; } ;;
+   { (exit 1); exit 1; }; }
+fi
+
+
+if test $coin_has_osi != unavailable &&
+   test $coin_has_osi != skipping; then
+  case $CXX in
+    cl*)
+       osilib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libOsi.lib';;
+     *)
+       osilib="-L\$(INSTALLIBDIR) -lOsi";;
   esac
 
+  else
+    { { echo "$as_me:$LINENO: error: cannot find Osi which is necessary to build OS" >&5
+echo "$as_me: error: cannot find Osi which is necessary to build OS" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+if test $coin_has_dylp != unavailable &&
+   test $coin_has_dylp != skipping; then
+  case $CXX in
+    cl*)
+       dylplib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libDylp.lib'
+       osidylplib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libOsiDylp.lib';;
+     *)
+       dylplib="-L\$(INSTALLIBDIR) -lDylp"
+       osidylplib="-L\$(INSTALLIBDIR) -lOsiDylp";;
+  esac
+
+
+fi
+
+
+if test $coin_has_vol != unavailable &&
+   test $coin_has_vol != skipping; then
+  case $CXX in
+    cl*)
+       vollib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libVol.lib'
+       osivollib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libVol.lib';;
+     *)
+       vollib="-L\$(INSTALLIBDIR) -lVol"
+       osivollib="-L\$(INSTALLIBDIR) -lOsiVol";;
+  esac
+
+
+fi
+
+
+if test $coin_has_symphony != unavailable &&
+   test $coin_has_symphony != skipping; then
+  case $CXX in
+    cl*)
+       symphonylib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libSym.lib'
+       osisymphonylib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libOsiSym.lib';;
+     *)
+       symphonylib="-L\$(INSTALLIBDIR) -lSym"
+       osisymphonylib="-L\$(INSTALLIBDIR) -lOsiSym";;
+  esac
+
+
+fi
+
+if test $coin_has_ipopt != unavailable &&
+   test $coin_has_ipopt != skipping; then
+  case $CXX in
+    cl*)
+       ipoptlib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libipopt.lib';;
+     *)
+       ipoptlib="-L\$(INSTALLIBDIR) -lipopt";;
+  esac
+
+fi
 
 #############################################################################
 #                             Third party solvers                           #
@@ -27237,9 +27348,9 @@ _ACEOF
 # The following one is for the example makefiles
 case $CXX in
   cl*)
-    oslib='`$(CYGPATH_W) $(OSLIBDIR)`\\libOS.lib';;
+    oslib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libOS.lib';;
   *)
-    oslib="-L\$(OSLIBDIR) -lOS";;
+    oslib="-L\$(INSTALLIBDIR) -lOS";;
 esac
 
 
@@ -28598,6 +28709,20 @@ s,@CPPADSRCDIR@,$CPPADSRCDIR,;t t
 s,@CPPADOBJDIR@,$CPPADOBJDIR,;t t
 s,@COIN_HAS_CPPAD_TRUE@,$COIN_HAS_CPPAD_TRUE,;t t
 s,@COIN_HAS_CPPAD_FALSE@,$COIN_HAS_CPPAD_FALSE,;t t
+s,@coinutilslib@,$coinutilslib,;t t
+s,@clplib@,$clplib,;t t
+s,@osiclplib@,$osiclplib,;t t
+s,@cbclib@,$cbclib,;t t
+s,@osicbclib@,$osicbclib,;t t
+s,@cgllib@,$cgllib,;t t
+s,@osilib@,$osilib,;t t
+s,@dylplib@,$dylplib,;t t
+s,@osidylplib@,$osidylplib,;t t
+s,@vollib@,$vollib,;t t
+s,@osivollib@,$osivollib,;t t
+s,@symphonylib@,$symphonylib,;t t
+s,@osisymphonylib@,$osisymphonylib,;t t
+s,@ipoptlib@,$ipoptlib,;t t
 s,@CPXINCDIR@,$CPXINCDIR,;t t
 s,@CPXLIB@,$CPXLIB,;t t
 s,@COIN_HAS_CPX_TRUE@,$COIN_HAS_CPX_TRUE,;t t
