update configure.ac for ipopt

diff --git a/OS/configure b/OS/configure
--- a/OS/configure
+++ b/OS/configure
@@ -21248,9 +21248,9 @@ echo "$as_me: error: You need to specify both --with-ipopt-incdir and --with-ipo
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
   # Check if the given header file is there
-  as_ac_File=`echo "ac_cv_file_$IPOPTINCDIR/IpOptConfig.h" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $IPOPTINCDIR/IpOptConfig.h" >&5
-echo $ECHO_N "checking for $IPOPTINCDIR/IpOptConfig.h... $ECHO_C" >&6
+  as_ac_File=`echo "ac_cv_file_$IPOPTINCDIR/IpoptConfig.h" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $IPOPTINCDIR/IpoptConfig.h" >&5
+echo $ECHO_N "checking for $IPOPTINCDIR/IpoptConfig.h... $ECHO_C" >&6
 if eval "test \"\${$as_ac_File+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -21258,7 +21258,7 @@ else
   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
 echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
    { (exit 1); exit 1; }; }
-if test -r "$IPOPTINCDIR/IpOptConfig.h"; then
+if test -r "$IPOPTINCDIR/IpoptConfig.h"; then
   eval "$as_ac_File=yes"
 else
   eval "$as_ac_File=no"
@@ -21269,8 +21269,8 @@ echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
 if test `eval echo '${'$as_ac_File'}'` = yes; then
   :
 else
-  { { echo "$as_me:$LINENO: error: Cannot find file IpOptConfig.h in $IPOPTINCDIR" >&5
-echo "$as_me: error: Cannot find file IpOptConfig.h in $IPOPTINCDIR" >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find file IpoptConfig.h in $IPOPTINCDIR" >&5
+echo "$as_me: error: Cannot find file IpoptConfig.h in $IPOPTINCDIR" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
