add Bcp

diff --git a/OS/configure b/OS/configure
--- a/OS/configure
+++ b/OS/configure
@@ -472,7 +472,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX F77 ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS FFLAGS ac_ct_F77 MPIF77 FLIBS EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS OSSRCDIR OSOBJDIR OSDOCDIR COIN_HAS_OS_TRUE COIN_HAS_OS_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COINUTILSDOCDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE OSISRCDIR OSIOBJDIR OSIDOCDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE CLPSRCDIR CLPOBJDIR CLPDOCDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE CBCSRCDIR CBCOBJDIR CBCDOCDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE CGLSRCDIR CGLOBJDIR CGLDOCDIR COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE SYMPHONYSRCDIR SYMPHONYOBJDIR SYMPHONYDOCDIR COIN_HAS_SYMPHONY_TRUE COIN_HAS_SYMPHONY_FALSE DYLPSRCDIR DYLPOBJDIR DYLPDOCDIR COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE VOLSRCDIR VOLOBJDIR VOLDOCDIR COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE IPOPTSRCDIR IPOPTOBJDIR IPOPTDOCDIR COIN_HAS_IPOPT_TRUE COIN_HAS_IPOPT_FALSE COUENNESRCDIR COUENNEOBJDIR COUENNEDOCDIR COIN_HAS_COUENNE_TRUE COIN_HAS_COUENNE_FALSE BONMINSRCDIR BONMINOBJDIR BONMINDOCDIR COIN_HAS_BONMIN_TRUE COIN_HAS_BONMIN_FALSE CPPADSRCDIR CPPADOBJDIR CPPADDOCDIR COIN_HAS_CPPAD_TRUE COIN_HAS_CPPAD_FALSE COMPILE_BONCOUENNE_TRUE COMPILE_BONCOUENNE_FALSE coinutilslib clplib osiclplib cbclib osicbclib cgllib osilib osiglpklib dylplib osidylplib vollib osivollib symphonylib osisymphonylib ipoptlib couennelib bonminlib CPXINCDIR CPXLIB COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE LINDOINCDIR LINDOLIB COIN_HAS_LINDO_TRUE COIN_HAS_LINDO_FALSE KNITROINCDIR KNITROLIB COIN_HAS_KNITRO_TRUE COIN_HAS_KNITRO_FALSE GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE ASLLIB ASL_CPPFLAGS COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE OPENMP_TRUE OPENMP_FALSE USEMULTIPLYDEFINED_TRUE USEMULTIPLYDEFINED_FALSE YACC OSROOT_DIR oslib USE_ASL_LIB LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX F77 ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS FFLAGS ac_ct_F77 MPIF77 FLIBS EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS OSSRCDIR OSOBJDIR OSDOCDIR COIN_HAS_OS_TRUE COIN_HAS_OS_FALSE BCPSRCDIR BCPOBJDIR BCPDOCDIR COIN_HAS_BCP_TRUE COIN_HAS_BCP_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COINUTILSDOCDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE OSISRCDIR OSIOBJDIR OSIDOCDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE CLPSRCDIR CLPOBJDIR CLPDOCDIR COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE CBCSRCDIR CBCOBJDIR CBCDOCDIR COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE CGLSRCDIR CGLOBJDIR CGLDOCDIR COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE SYMPHONYSRCDIR SYMPHONYOBJDIR SYMPHONYDOCDIR COIN_HAS_SYMPHONY_TRUE COIN_HAS_SYMPHONY_FALSE DYLPSRCDIR DYLPOBJDIR DYLPDOCDIR COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE VOLSRCDIR VOLOBJDIR VOLDOCDIR COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE IPOPTSRCDIR IPOPTOBJDIR IPOPTDOCDIR COIN_HAS_IPOPT_TRUE COIN_HAS_IPOPT_FALSE COUENNESRCDIR COUENNEOBJDIR COUENNEDOCDIR COIN_HAS_COUENNE_TRUE COIN_HAS_COUENNE_FALSE BONMINSRCDIR BONMINOBJDIR BONMINDOCDIR COIN_HAS_BONMIN_TRUE COIN_HAS_BONMIN_FALSE CPPADSRCDIR CPPADOBJDIR CPPADDOCDIR COIN_HAS_CPPAD_TRUE COIN_HAS_CPPAD_FALSE COMPILE_BONCOUENNE_TRUE COMPILE_BONCOUENNE_FALSE coinutilslib clplib osiclplib cbclib osicbclib cgllib osilib osiglpklib dylplib osidylplib vollib osivollib bcplib symphonylib osisymphonylib ipoptlib couennelib bonminlib CPXINCDIR CPXLIB COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE LINDOINCDIR LINDOLIB COIN_HAS_LINDO_TRUE COIN_HAS_LINDO_FALSE KNITROINCDIR KNITROLIB COIN_HAS_KNITRO_TRUE COIN_HAS_KNITRO_FALSE GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE ASLLIB ASL_CPPFLAGS COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE OPENMP_TRUE OPENMP_FALSE USEMULTIPLYDEFINED_TRUE USEMULTIPLYDEFINED_FALSE YACC OSROOT_DIR oslib USE_ASL_LIB LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -23692,6 +23692,64 @@ fi
 echo "$as_me:$LINENO: result: $coin_has_os" >&5
 echo "${ECHO_T}$coin_has_os" >&6
 
+echo "$as_me:$LINENO: checking for COIN project Bcp" >&5
+echo $ECHO_N "checking for COIN project Bcp... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_bcp=unavailable
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = Bcp; then
+      coin_has_bcp=skipping
+    fi
+  done
+fi
+
+if test $coin_has_bcp != skipping; then
+  if test $PACKAGE_TARNAME = bcp; then
+    coin_has_bcp=.
+  else
+    if test -d $srcdir/../Bcp; then
+      coin_has_bcp=../Bcp
+    fi
+  fi
+fi
+
+if test $coin_has_bcp != unavailable &&
+   test $coin_has_bcp != skipping; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_BCP 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  BCPSRCDIR=`cd $srcdir/$coin_has_bcp; pwd`
+
+  BCPOBJDIR=`pwd`/$coin_has_bcp
+
+  BCPDOCDIR=$abs_lib_dir/../share/doc/coin/Bcp
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_bcp != unavailable &&
+                test $coin_has_bcp != skipping; then
+  COIN_HAS_BCP_TRUE=
+  COIN_HAS_BCP_FALSE='#'
+else
+  COIN_HAS_BCP_TRUE='#'
+  COIN_HAS_BCP_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_bcp" >&5
+echo "${ECHO_T}$coin_has_bcp" >&6
+
 echo "$as_me:$LINENO: checking for COIN project CoinUtils" >&5
 echo $ECHO_N "checking for COIN project CoinUtils... $ECHO_C" >&6
 
@@ -24531,6 +24589,9 @@ if test $coin_has_dylp != unavailable &&
 fi
 
 
+
+
+
 if test $coin_has_dylp != unavailable &&
    test $coin_has_dylp != skipping; then
   case $CXX in
@@ -24557,6 +24618,18 @@ if test $coin_has_vol != unavailable &&
        osivollib="-L\$(INSTALLIBDIR) -lOsiVol";;
   esac
 
+
+fi
+
+
+if test $coin_has_bcp != unavailable &&
+   test $coin_has_bcp != skipping; then
+  case $CXX in
+    cl*)
+       bcplib='`$(CYGPATH_W) $(INSTALLIBDIR)`\\libbcp.lib';;
+     *)
+       bcplib="-L\$(INSTALLIBDIR) -lBcp";;
+  esac
 
 fi
 
@@ -30468,7 +30541,7 @@ fi
 
 # Here list all the files that configure should create (except for the
 # configuration header file)
-                                                                                                                                                                                                                                                          ac_config_files="$ac_config_files Makefile src/Makefile src/OSAgent/Makefile src/OSUtils/Makefile src/OSCommonInterfaces/Makefile src/OSSolverInterfaces/Makefile src/OSModelInterfaces/Makefile src/OSParsers/Makefile test/Makefile examples/instanceGenerator/Makefile examples/osTestCode/Makefile examples/algorithmicDiff/Makefile examples/addCuts/Makefile examples/osRemoteTest/Makefile examples/template/Makefile examples/CppAD/Makefile CoinAllExamples/instanceGenerator/Makefile CoinAllExamples/osTestCode/Makefile CoinAllExamples/addCuts/Makefile CoinAllExamples/template/Makefile CoinAllExamples/CppAD/Makefile applications/Makefile applications/amplClient/Makefile applications/fileUpload/Makefile os_addlibs.txt"
+                                                                                                                                                                                                                                                                    ac_config_files="$ac_config_files Makefile src/Makefile src/OSAgent/Makefile src/OSUtils/Makefile src/OSCommonInterfaces/Makefile src/OSSolverInterfaces/Makefile src/OSModelInterfaces/Makefile src/OSParsers/Makefile test/Makefile examples/instanceGenerator/Makefile examples/osTestCode/Makefile examples/algorithmicDiff/Makefile examples/addCuts/Makefile examples/osRemoteTest/Makefile examples/template/Makefile examples/CppAD/Makefile examples/branchCutPrice/Makefile CoinAllExamples/instanceGenerator/Makefile CoinAllExamples/osTestCode/Makefile CoinAllExamples/addCuts/Makefile CoinAllExamples/template/Makefile CoinAllExamples/CppAD/Makefile applications/Makefile applications/amplClient/Makefile applications/fileUpload/Makefile os_addlibs.txt"
 
 
 
@@ -30671,6 +30744,13 @@ if test -z "${COIN_HAS_OS_TRUE}" && test -z "${COIN_HAS_OS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_OS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"COIN_HAS_OS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_BCP_TRUE}" && test -z "${COIN_HAS_BCP_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_BCP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_BCP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -31288,6 +31368,7 @@ do
   "examples/osRemoteTest/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/osRemoteTest/Makefile" ;;
   "examples/template/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/template/Makefile" ;;
   "examples/CppAD/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/CppAD/Makefile" ;;
+  "examples/branchCutPrice/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/branchCutPrice/Makefile" ;;
   "CoinAllExamples/instanceGenerator/Makefile" ) CONFIG_FILES="$CONFIG_FILES CoinAllExamples/instanceGenerator/Makefile" ;;
   "CoinAllExamples/osTestCode/Makefile" ) CONFIG_FILES="$CONFIG_FILES CoinAllExamples/osTestCode/Makefile" ;;
   "CoinAllExamples/addCuts/Makefile" ) CONFIG_FILES="$CONFIG_FILES CoinAllExamples/addCuts/Makefile" ;;
@@ -31493,6 +31574,11 @@ s,@OSOBJDIR@,$OSOBJDIR,;t t
 s,@OSDOCDIR@,$OSDOCDIR,;t t
 s,@COIN_HAS_OS_TRUE@,$COIN_HAS_OS_TRUE,;t t
 s,@COIN_HAS_OS_FALSE@,$COIN_HAS_OS_FALSE,;t t
+s,@BCPSRCDIR@,$BCPSRCDIR,;t t
+s,@BCPOBJDIR@,$BCPOBJDIR,;t t
+s,@BCPDOCDIR@,$BCPDOCDIR,;t t
+s,@COIN_HAS_BCP_TRUE@,$COIN_HAS_BCP_TRUE,;t t
+s,@COIN_HAS_BCP_FALSE@,$COIN_HAS_BCP_FALSE,;t t
 s,@COINUTILSSRCDIR@,$COINUTILSSRCDIR,;t t
 s,@COINUTILSOBJDIR@,$COINUTILSOBJDIR,;t t
 s,@COINUTILSDOCDIR@,$COINUTILSDOCDIR,;t t
@@ -31567,6 +31653,7 @@ s,@dylplib@,$dylplib,;t t
 s,@osidylplib@,$osidylplib,;t t
 s,@vollib@,$vollib,;t t
 s,@osivollib@,$osivollib,;t t
+s,@bcplib@,$bcplib,;t t
 s,@symphonylib@,$symphonylib,;t t
 s,@osisymphonylib@,$osisymphonylib,;t t
 s,@ipoptlib@,$ipoptlib,;t t
