fix configure.ac

diff --git a/OS/configure b/OS/configure
--- a/OS/configure
+++ b/OS/configure
@@ -22365,31 +22365,43 @@ echo "$as_me:$LINENO: result: $coin_has_cppad" >&5
 echo "${ECHO_T}$coin_has_cppad" >&6
 
 
-#############################################################################
-#                              Make sure certain projects are present                      #
-#############################################################################
 
-case $coin_has_cppad in  (unavailable | skipping)    { { echo "$as_me:$LINENO: error: cannot find CppAD: CppAD is required for OS" >&5
-echo "$as_me: error: cannot find CppAD: CppAD is required for OS" >&2;}
-   { (exit 1); exit 1; }; }esac
+  case $coin_has_cppad in
+     unavailable|skipping)
+         { { echo "$as_me:$LINENO: error: cannot find CppAD" >&5
+echo "$as_me: error: cannot find CppAD" >&2;}
+   { (exit 1); exit 1; }; } ;;
+  esac
+
+  case $coin_has_coinutils in
+     unavailable|skipping)
+         { { echo "$as_me:$LINENO: error: cannot find CoinUtils" >&5
+echo "$as_me: error: cannot find CoinUtils" >&2;}
+   { (exit 1); exit 1; }; } ;;
+  esac
 
 
-case $coin_has_coinutils in  (unavailable | skipping)    { { echo "$as_me:$LINENO: error: cannot find CoinUtils: CoinUtils is required for OS" >&5
-echo "$as_me: error: cannot find CoinUtils: CoinUtils is required for OS" >&2;}
-   { (exit 1); exit 1; }; }esac
+  case $coin_has_clp in
+     unavailable|skipping)
+         { { echo "$as_me:$LINENO: error: cannot find Clp" >&5
+echo "$as_me: error: cannot find Clp" >&2;}
+   { (exit 1); exit 1; }; } ;;
+  esac
 
+  case $coin_has_cbc in
+     unavailable|skipping)
+         { { echo "$as_me:$LINENO: error: cannot find Cbc" >&5
+echo "$as_me: error: cannot find Cbc" >&2;}
+   { (exit 1); exit 1; }; } ;;
+  esac
 
-case $coin_has_clp in  (unavailable | skipping)    { { echo "$as_me:$LINENO: error: cannot find Clp: Clp is required for OS" >&5
-echo "$as_me: error: cannot find Clp: Clp is required for OS" >&2;}
-   { (exit 1); exit 1; }; }esac
+  case $coin_has_cgl in
+     unavailable|skipping)
+         { { echo "$as_me:$LINENO: error: cannot find Cgl" >&5
+echo "$as_me: error: cannot find Cgl" >&2;}
+   { (exit 1); exit 1; }; } ;;
+  esac
 
-case $coin_has_cbc in  (unavailable | skipping)    { { echo "$as_me:$LINENO: error: cannot find Cbc: Cbc is required for OS" >&5
-echo "$as_me: error: cannot find Cbc: Cbc is required for OS" >&2;}
-   { (exit 1); exit 1; }; }esac
-
-case $coin_has_cgl in  (unavailable | skipping)    { { echo "$as_me:$LINENO: error: cannot find Cgl: Cgl is required for OS" >&5
-echo "$as_me: error: cannot find Cgl: Cgl is required for OS" >&2;}
-   { (exit 1); exit 1; }; }esac
 
 #############################################################################
 #                             Third party solvers                           #
