final instdir commits for tonight

diff --git a/OS/configure b/OS/configure
--- a/OS/configure
+++ b/OS/configure
@@ -23795,13 +23795,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_os=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   OSINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of OS with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of OS with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -23960,13 +23961,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_bcp=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   BCPINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Bcp with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of Bcp with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -24125,13 +24127,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_coinutils=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   COINUTILSINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of CoinUtils with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of CoinUtils with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -24290,13 +24293,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_osi=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   OSIINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Osi with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of Osi with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -24455,13 +24459,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_clp=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   CLPINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Clp with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of Clp with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -24620,13 +24625,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_cbc=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   CBCINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Cbc with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of Cbc with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -24785,13 +24791,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_cgl=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   CGLINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Cgl with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of Cgl with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -24950,13 +24957,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_symphony=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   SYMPHONYINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of SYMPHONY with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of SYMPHONY with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -25115,13 +25123,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_dylp=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   DYLPINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of DyLP with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of DyLP with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -25280,13 +25289,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_vol=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   VOLINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Vol with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of Vol with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -25445,13 +25455,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_ipopt=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   IPOPTINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Ipopt with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of Ipopt with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -25610,13 +25621,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_couenne=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   COUENNEINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Couenne with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of Couenne with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -25775,13 +25787,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_bonmin=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   BONMININSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Bonmin with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of Bonmin with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
@@ -25940,13 +25953,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_cppad=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   CPPADINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of cppad with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of cppad with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
